name: cog_ieeg_release_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.0.4
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - ansicolors=1.1.8
  - anyio=4.4.0
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-blosc2=2.15.0
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-option-group=0.5.6
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - darkdetect=0.8.0
  - dav1d=1.2.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - deepdiff=7.0.1
  - defusedxml=0.7.1
  - deprecated=1.2.14
  - dipy=1.9.0
  - double-conversion=3.3.0
  - edfio=0.4.3
  - eeglabio=0.0.2.post4
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - future=1.0.0
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.13
  - gst-plugins-base=1.24.5
  - gstreamer=1.24.5
  - h11=0.14.0
  - h2=4.1.0
  - h5io=0.2.3
  - h5py=3.11.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.6.1
  - imageio=2.34.2
  - imageio-ffmpeg=0.5.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isodate=0.6.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsoncpp=1.9.5
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.8
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflang=5.0.0
  - libglib=2.80.2
  - libhwloc=2.11.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libmatio=1.5.27
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - littleutils=0.2.2
  - llvm-meta=5.0.0
  - llvmlite=0.43.0
  - loguru=0.7.2
  - lxml=5.2.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - matplotlib-venn=0.11.10
  - mffpy=0.9.0
  - mistune=3.0.2
  - mkl=2023.2.0
  - mne=1.7.1
  - mne-base=1.7.1
  - mne-bids=0.15.0
  - mne-qt-browser=0.6.3
  - more-itertools=10.3.0
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nibabel=5.2.1
  - nilearn=0.10.4
  - nlohmann_json=3.11.3
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numexpr=2.10.0
  - numpy=1.26.4
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openmeeg=2.5.11
  - openmp=5.0.0
  - openssl=3.3.1
  - ordered-set=4.1.0
  - orjson=3.10.6
  - outdated=0.2.2
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandas-flavor=0.6.0
  - pandoc=3.2.1
  - pandocfilters=1.5.0
  - papermill=2.6.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pingouin=0.5.4
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - ply=3.11
  - pooch=1.8.2
  - progressbar2=4.4.2
  - proj=9.3.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pybv=0.7.5
  - pycparser=2.22
  - pydicom=2.4.4
  - pygments=2.18.0
  - pymatreader=0.0.32
  - pyopengl=3.1.6
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtgraph=0.13.7
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-picard=0.7
  - python-tzdata=2024.1
  - python-utils=3.8.2
  - python_abi=3.12
  - pytz=2024.1
  - pyvista=0.44.0
  - pyvistaqt=0.11.1
  - pywavelets=1.6.0
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qdarkstyle=3.2.3
  - qt-main=5.15.8
  - qt6-main=6.7.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - rav1e=0.6.6
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.19.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - scooby=0.10.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=70.1.1
  - setuptools-scm=8.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - svt-av1=2.1.2
  - tabulate=0.9.0
  - tbb=2021.12.0
  - tbb-devel=2021.12.0
  - tenacity=8.2.2
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2024.7.2
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - trame=3.6.3
  - trame-client=3.2.1
  - trame-server=3.0.3
  - trame-vtk=2.8.9
  - trame-vuetify=2.6.1
  - trx-python=0.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - utfcpp=4.0.5
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - vtk=9.3.1
  - vtk-base=9.3.1
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.16.0
  - wslink=2.1.1
  - x264=1!164.3095
  - x265=3.5
  - xarray=2024.6.0
  - xlrd=2.0.1
  - xmltodict=0.13.0
  - xnat=0.6.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.19.2
  - zlib=1.3.1
  - zlib-ng=2.2.1
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
    - git+https://github.com/Cogitate-consortium/iEEG-data-release.git@main#egg=cog_ieeg
